Add quality level 1
micro-ROS/rmw-microxrcedds pull request #112
Opened 2021-03-11 09:47 UTC by pablogs9

2021-03-11 15:01 UTC, ralph-lange approved these changes
Looks good to me. Found only one super-little formatting issue.

2021-03-11 15:02 UTC, pablogs9 commented on rmw_microxrcedds_c/CONTRIBUTING.md
> +Contributors must sign-off each commit by adding a `Signed-off-by: ...` line to commit messages to certify that they have the right to submit the code they are contributing to the project according t
![image](https://user-images.githubusercontent.com/7647884/110807347-38311700-8283-11eb-898d-b7783ee8f15e.png)

Is this right?

2021-03-11 15:03 UTC, pablogs9 commented on rmw_microxrcedds_c/CONTRIBUTING.md
> +- [Contribution Guidelines](#contribution-guidelines)
```suggestion
  - [Contribution Guidelines](#contribution-guidelines)
```

2021-03-11 15:07 UTC, ralph-lange commented on rmw_microxrcedds_c/CONTRIBUTING.md
> +Contributors must sign-off each commit by adding a `Signed-off-by: ...` line to commit messages to certify that they have the right to submit the code they are contributing to the project according t
Perfect!

2021-03-11 15:10 UTC, pablogs9 commented on rmw_microxrcedds_c/CONTRIBUTING.md
> +- [Contribution Guidelines](#contribution-guidelines)
No, `Contribution Guidelines` is the main section and the others are subsections

2021-03-11 15:10 UTC, pablogs9 commented on rmw_microxrcedds_c/CONTRIBUTING.md
> +- [Contribution Guidelines](#contribution-guidelines)
Same as in rmw

2021-03-11 16:07 UTC, ralph-lange approved these changes

2021-03-22 15:37 UTC, FranFin requested changes

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/PLATFORM_SUPPORT.md
> +The CI is expected to be run at least within a week of relevant changes for the current release of **rmw_microxrcedds_c**.
```suggestion
The CI is expected to be run at least within a week from the last relevant changes for the current release of **rmw_microxrcedds_c**.
```

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/PLATFORM_SUPPORT.md
> +The development team does not run the unit test suite or perform any other tests on platforms in Tier 3.
```suggestion
The development team does not run the unit test suite nor perform any other tests on platforms in Tier 3.
```

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/PLATFORM_SUPPORT.md
> +* Nuttx
```suggestion
* NuttX
```

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/QUALITY.md
> +**rmw_microxrcedds_c** is a RMW implementation for ROS and micro-ROS that uses [eProsima Micro XRCE-DDS](https://github.com/eProsima/Micro-XRCE-DDS) as middleware library.
```suggestion
**rmw_microxrcedds_c** is a RMW implementation for ROS 2 and micro-ROS that uses [eProsima Micro XRCE-DDS](https://github.com/eProsima/Micro-XRCE-DDS) as a middleware library.
```

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/QUALITY.md
> +All installed headers are in the include directory of the package, headers in any other folders are not installed and considered private.
```suggestion
All installed headers are in the `include` directory of the package. Headers in any other folders are not installed and considered as private.
```

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/QUALITY.md
> +Any ABI break in **rmw_microxrcedds_c** will be done between minor versions and it should be clearly stated on the release notes.
```suggestion
Any ABI break in **rmw_microxrcedds_c** will be done between minor versions and it should be clearly stated in the release notes.
```

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/QUALITY.md
> +Additionally, all pull requests must have a positive review from one other contributor that did not author the pull request.
```suggestion
Additionally, all pull requests must have at least one positive review from another contributor that did not author the pull request.
```

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/QUALITY.md
> +Some of the **rmw_microxrcedds_c** features are documented on the repository level [README](../README.md).
```suggestion
Some of the **rmw_microxrcedds_c** features are documented at the repository level [README](../README.md).
```

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/QUALITY.md
> +**rmw_microxrcedds_c** copyright holder provide a statement of copyright in each source file.
```suggestion
The **rmw_microxrcedds_c** copyright holder provides a statement of copyright in each source file.
```

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/QUALITY.md
> +Among the CI tests there are tests that ensures that every pull request is compliant with the code style.
```suggestion
Among the CI tests, there are tests that ensure that every pull request is compliant with the code style.
```

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/QUALITY.md
> +**rmw_microxrcedds_c** supports the all the platforms that are intended for. Those included GNU/Linux and POSIX systems and all the major embedded RTOS such as Zephyr RTOS, FreeRTOS and Nuttx. Window
Would it be possible to reformulate this?

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/QUALITY.md
> +The chart below compares the requirements in the [REP-2004](https://www.ros.org/reps/rep-2004.html#quality-level-comparison-chart) with the current state of **rmw_microxrcedds_c**
```suggestion
The chart below compares the requirements in the [REP-2004](https://www.ros.org/reps/rep-2004.html#quality-level-comparison-chart) with the current state of **rmw_microxrcedds_c**.
```

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/README.md
> +`rmw_microxrcedds_c` implements the ROS middleware interface using eProsima Micro XRCE-DDS middleware.
```suggestion
`rmw_microxrcedds_c` implements the ROS middleware interface using *eProsima Micro XRCE-DDS* as a middleware.
```

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/VERSIONING.md
> +Starting on v1.0.0, the version numbers for this library will adhere to the versioning policies defined by [Semantic Versioning](https://semver.org/).
```suggestion
Starting with v1.0.0, the version numbers for this library will adhere to the versioning policies defined by [Semantic Versioning](https://semver.org/).
```

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/QUALITY.md
> +**rmw_microxrcedds_c** uses and passes all the standard linters and static analysis tools for a C++ package as described in the [ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Dev
```suggestion
**rmw_microxrcedds_c** uses and passes all the standard linters and static analysis tools for a C99 package as described in the [ROS 2 Developer Guide](https://index.ros.org/doc/ros2/Contributing/Developer-Guide/#linters).
```

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/VERSIONING.md
> +If an ABI break is required, it should be done between minor versions, and it should be clearly stated on the release notes.
```suggestion
If an ABI break is required, it should be done between minor versions, and it should be clearly stated in the release notes.
```

2021-03-22 15:37 UTC, FranFin commented on rmw_microxrcedds_c/VERSIONING.md
> +The changes included on each version can be found in the [release notes](https://github.com/micro-ROS/rmw-microxrcedds/releases)
```suggestion
The changes included in each version can be found in the [release notes](https://github.com/micro-ROS/rmw-microxrcedds/releases)
```

2021-03-22 15:42 UTC, pablogs9 commented on rmw_microxrcedds_c/QUALITY.md
> +**rmw_microxrcedds_c** supports the all the platforms that are intended for. Those included GNU/Linux and POSIX systems and all the major embedded RTOS such as Zephyr RTOS, FreeRTOS and Nuttx. Window
```suggestion
**rmw_microxrcedds_c** is intended for micro-ROS and embedded platforms, so the officially supported platforms are not the same as in ROS 2. Those includes GNU/Linux and POSIX systems and all the major embedded RTOS such as Zephyr RTOS, FreeRTOS and NuttX. Windows is not included as Tier 1 platform because it is irrelevant to the nature of this package.
```

@FranFin

2021-03-22 15:47 UTC, FranFin commented on rmw_microxrcedds_c/QUALITY.md
> +**rmw_microxrcedds_c** supports the all the platforms that are intended for. Those included GNU/Linux and POSIX systems and all the major embedded RTOS such as Zephyr RTOS, FreeRTOS and Nuttx. Window
```suggestion
**rmw_microxrcedds_c** is intended for micro-ROS and therefore to run on embedded platforms, so the officially supported platforms are not the same as in ROS 2. These include GNU/Linux and POSIX systems and all the major embedded RTOS such as Zephyr RTOS, FreeRTOS, and NuttX. Windows is not included as a Tier 1 platform because it is not relevant for this package due to its nature.
```

2021-03-22 15:54 UTC, FranFin requested changes

2021-03-22 15:54 UTC, FranFin commented on rmw_microxrcedds_c/QUALITY.md
> +**rmw_microxrcedds_c** checks the coverage of every commit. Last coverage can be seen in [Codecov](https://app.codecov.io/gh/micro-ROS/rmw-microxrcedds/commits).
```suggestion
**rmw_microxrcedds_c** checks the coverage of every commit. Last coverage assessment can be seen in [Codecov](https://app.codecov.io/gh/micro-ROS/rmw-microxrcedds/commits).
```

2021-03-23 11:16 UTC, FranFin approved these changes

2021-03-23 11:22 UTC, merged

2021-03-31 14:06 UTC, JanStaschulat commented on rmw_microxrcedds_c/QUALITY.md
> +A full copy of the license can be found [here](LICENSE).
link is not correct: 
[here](../LICENSE)

2021-03-31 14:10 UTC, pablogs9 commented on rmw_microxrcedds_c/QUALITY.md
> +A full copy of the license can be found [here](LICENSE).
https://github.com/micro-ROS/rmw-microxrcedds/pull/120