Static mem pools
micro-ROS/rmw-microxrcedds pull request #113
Opened 2021-03-18 09:28 UTC by pablogs9

This PR:
- Refactors incoming buffers to a shared static approach
- Refactor the XML/ref static buffer handling

2021-03-18 09:34 UTC, pablogs9 commented
Marie Kondo

2021-03-18 09:43 UTC, pablogs9 commented
Marie Kondo

2021-03-18 12:06 UTC, jamoralp commented on rmw_microxrcedds_c/test/test_sizes.cpp
>      fprintf(stderr, "# Static memory analisys \n");
```suggestion
    fprintf(stderr, "# Static memory analysis \n");
```

2021-03-26 09:02 UTC, jamoralp requested changes

2021-03-26 09:02 UTC, jamoralp commented on rmw_microxrcedds_c/src/rmw_take.c
> +        static_buffer->lenght);
```suggestion
        static_buffer->length);
```

2021-03-26 09:02 UTC, jamoralp commented on rmw_microxrcedds_c/src/types.h
> +    size_t lenght;
```suggestion
    size_t length;
```

2021-03-26 09:27 UTC, pablogs9 commented on rmw_microxrcedds_c/src/memory.h
> +// #error "this should be locked!"
```suggestion
```

2021-03-26 09:50 UTC, Acuadros95 approved these changes

2021-03-26 10:01 UTC, merged