Add external transport API
micro-ROS/rmw-microxrcedds pull request #91
Opened 2021-01-25 08:34 UTC by pablogs9

2021-02-03 07:20 UTC, pablogs9 commented
This PR should target `foxy`

2021-02-05 11:29 UTC, jamoralp commented on rmw_microxrcedds_c/include/rmw_uros/options.h
> +typedef struct rmw_uxrce_transport_params_t
for now, this struct declaration fits ok here, but after I finish refactoring transports init/fini functions in a separate file (namely, transports.h) I could move it there. What do you think @pablogs9 ¿

2021-02-05 11:29 UTC, jamoralp approved these changes

2021-02-05 11:56 UTC, pablogs9 commented on rmw_microxrcedds_c/include/rmw_uros/options.h
> +typedef struct rmw_uxrce_transport_params_t
Ok

2021-02-08 08:56 UTC, jamoralp requested changes

2021-02-08 08:56 UTC, jamoralp commented on rmw_microxrcedds_c/src/rmw_init.c
> +  int fd = open(context->impl->transport_params.serial_device, O_RDWR | O_NOCTTY);
This cannot be working. It should be changed to 
```suggestion
  int fd = open(options->impl->transport_params.serial_device, O_RDWR | O_NOCTTY);
```

2021-02-09 10:43 UTC, jamoralp approved these changes

2021-02-09 10:43 UTC, merged